<?php

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}
	
	acf_add_local_field_group( array(
		'key' => 'group_664541a6c348d',
		'title' => 'Breadcrumbs',
		'fields' => array(
			array(
				'key' => 'field_664e674756c02',
				'label' => 'Separator',
				'name' => 'separator',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '/',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_664e674c56c03',
				'label' => 'Show home',
				'name' => 'show_home',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => 'acf-hide-label',
					'id' => '',
				),
				'default_value' => 'Show home',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'rs-utility-blocks/breadcrumbs',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '[RS Utility Blocks] ACF Block -> Breadcrumbs',
		'show_in_rest' => 0,
	) );
	
	acf_add_local_field_group( array(
		'key' => 'group_6619885838faf',
		'title' => 'Edit Profile',
		'fields' => array(
			array(
				'key' => 'field_66198857c8070',
				'label' => 'Fields',
				'name' => 'fields',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'choices' => array(
					'name' => 'Name',
					'email' => 'Email',
					'password' => 'Password',
					'bio' => 'Biographical Info',
					'website' => 'Website',
				),
				'default_value' => array(
					0 => 'name',
					1 => 'email',
					2 => 'password',
				),
				'return_format' => 'value',
				'multiple' => 1,
				'allow_null' => 0,
				'ui' => 1,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_66199f4675802',
				'label' => 'Show Confirm Email',
				'name' => 'show_confirm_email',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_66198857c8070',
							'operator' => '==',
							'value' => 'email',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => 'acf-hide-label',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'message' => 'Show confirm email field',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_6619a0a6c5e45',
				'label' => 'Show Confirm Password',
				'name' => 'show_confirm_password',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_66198857c8070',
							'operator' => '==',
							'value' => 'password',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => 'acf-hide-label',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'message' => 'Show confirm password field',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'rs-utility-blocks/edit-profile',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '[RS Utility Blocks] ACF Block -> Edit Profile',
		'show_in_rest' => 0,
		'qef_simple_location_rules' => false,
	) );
	
	acf_add_local_field_group( array(
		'key' => 'group_66394f3e0d9ca',
		'title' => 'Link Block',
		'fields' => array(
			array(
				'key' => 'field_66394f422742a',
				'label' => 'URL',
				'name' => 'url',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_66394f5e2742b',
				'label' => 'New Tab',
				'name' => 'new_tab',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => 'acf-hide-label',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'message' => 'Open in new tab',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_66394f6b2742c',
				'label' => 'Title (Hover Tooltip)',
				'name' => 'title',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'rs-utility-blocks/link-block',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '[RS Utility Blocks] ACF Block -> Link Block',
		'show_in_rest' => 0,
		'qef_simple_location_rules' => false,
	) );
	
	acf_add_local_field_group( array(
		'key' => 'group_65f2e54f471c2',
		'title' => 'Login Form',
		'fields' => array(
			array(
				'key' => 'field_65f2e54f00886',
				'label' => 'Settings',
				'name' => 'settings',
				'aria-label' => '',
				'type' => 'checkbox',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'choices' => array(
					'show_forgot_password' => 'Show forgot password',
					'show_logout_link' => 'Show logout link (if logged in)',
					'show_register_link' => 'Show create account link',
					'disable_custom_style' => 'Disable custom styles',
				),
				'default_value' => array(
				),
				'return_format' => 'value',
				'allow_custom' => 0,
				'layout' => 'vertical',
				'toggle' => 0,
				'save_custom' => 0,
				'custom_choice_button_text' => 'Add new choice',
			),
			array(
				'key' => 'field_65f2e57f00887',
				'label' => 'Create Account URL',
				'name' => 'create_account_url',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_65f2e54f00886',
							'operator' => '==',
							'value' => 'show_register_link',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_65f2ef6272a08',
				'label' => 'Login Redirect',
				'name' => 'login_redirect',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'rs-utility-blocks/login-form',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '[RS Utility Blocks] ACF Block -> Login Form',
		'show_in_rest' => 0,
		'qef_simple_location_rules' => false,
	) );
	
	acf_add_local_field_group( array(
		'key' => 'group_663aa1c0cafe3',
		'title' => 'Mobile Menu Button',
		'fields' => array(
			array(
				'key' => 'field_663aa1c68ed43',
				'label' => 'Menu Slug',
				'name' => 'menu_slug',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'Create a separate mobile menu container elsewhere. Use the same slug on this menu button to link them together.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_663aa202dbda2',
				'label' => 'Appearance',
				'name' => 'appearance',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'choices' => array(
					'icon' => 'Icon Only',
					'text' => 'Text Only',
					'icontext' => 'Icon and Text',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_663aa227dbda3',
				'label' => 'Open Text',
				'name' => 'open_text',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_663aa202dbda2',
							'operator' => '==',
							'value' => 'text',
						),
					),
					array(
						array(
							'field' => 'field_663aa202dbda2',
							'operator' => '==',
							'value' => 'icontext',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'default_value' => 'Menu',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_663aa23fdbda5',
				'label' => 'Close Text',
				'name' => 'close_text',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_663aa202dbda2',
							'operator' => '==',
							'value' => 'text',
						),
					),
					array(
						array(
							'field' => 'field_663aa202dbda2',
							'operator' => '==',
							'value' => 'icontext',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'default_value' => 'Close',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_663aa288dbda8',
				'label' => 'Open Icon Type',
				'name' => 'open_icon_type',
				'aria-label' => '',
				'type' => 'button_group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_663aa202dbda2',
							'operator' => '==',
							'value' => 'icon',
						),
					),
					array(
						array(
							'field' => 'field_663aa202dbda2',
							'operator' => '==',
							'value' => 'icontext',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'choices' => array(
					'dashicons-menu' => '<span title="Menu" class="dashicons dashicons-menu"></span>',
					'dashicons-menu-alt' => '<span title="Menu Alt" class="dashicons dashicons-menu-alt"></span>',
					'dashicons-menu-alt2' => '<span title="Menu Alt 2" class="dashicons dashicons-menu-alt2"></span>',
					'dashicons-menu-alt3' => '<span title="Menu Alt 3" class="dashicons dashicons-menu-alt3"></span>',
					'text' => '<span title="Symbol (Trigram)">☰</span>',
					'custom' => 'Custom',
				),
				'default_value' => 'dashicons-menu',
				'return_format' => 'value',
				'allow_null' => 0,
				'layout' => 'horizontal',
			),
			array(
				'key' => 'field_663aa24bdbda6',
				'label' => 'Custom Open Icon',
				'name' => 'custom_open_icon',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_663aa202dbda2',
							'operator' => '==',
							'value' => 'icon',
						),
						array(
							'field' => 'field_663aa288dbda8',
							'operator' => '==',
							'value' => 'custom',
						),
					),
					array(
						array(
							'field' => 'field_663aa202dbda2',
							'operator' => '==',
							'value' => 'icontext',
						),
						array(
							'field' => 'field_663aa288dbda8',
							'operator' => '==',
							'value' => 'custom',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'return_format' => 'id',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'preview_size' => 'medium',
			),
			array(
				'key' => 'field_663aa3134ba21',
				'label' => 'Close Icon Type',
				'name' => 'close_icon_type',
				'aria-label' => '',
				'type' => 'button_group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_663aa202dbda2',
							'operator' => '==',
							'value' => 'icon',
						),
					),
					array(
						array(
							'field' => 'field_663aa202dbda2',
							'operator' => '==',
							'value' => 'icontext',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'choices' => array(
					'dashicons-no' => '<span title="Close" class="dashicons dashicons-no"></span>',
					'dashicons-no-alt' => '<span title="Close Alt" class="dashicons dashicons-no-alt"></span>',
					'text' => '<span title="Symbol (Times)">×</span>',
					'custom' => 'Custom',
				),
				'default_value' => 'dashicons-no',
				'return_format' => 'value',
				'allow_null' => 0,
				'layout' => 'horizontal',
			),
			array(
				'key' => 'field_663aa3524ba22',
				'label' => 'Custom Close Icon',
				'name' => 'custom_close_icon',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_663aa202dbda2',
							'operator' => '==',
							'value' => 'icon',
						),
						array(
							'field' => 'field_663aa3134ba21',
							'operator' => '==',
							'value' => 'custom',
						),
					),
					array(
						array(
							'field' => 'field_663aa202dbda2',
							'operator' => '==',
							'value' => 'icontext',
						),
						array(
							'field' => 'field_663aa3134ba21',
							'operator' => '==',
							'value' => 'custom',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'return_format' => 'id',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'preview_size' => 'medium',
			),
			array(
				'key' => 'field_663aa575edfc0',
				'label' => 'Icon Text Placement',
				'name' => 'icon_text_placement',
				'aria-label' => '',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_663aa202dbda2',
							'operator' => '==',
							'value' => 'icontext',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'choices' => array(
					'icon-first' => 'Icon after Text',
					'text-first' => 'Text after Icon',
				),
				'default_value' => '',
				'return_format' => 'value',
				'allow_null' => 0,
				'other_choice' => 0,
				'layout' => 'vertical',
				'save_other_choice' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'rs-utility-blocks/mobile-menu-button',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '[RS Utility Blocks] ACF Block -> Mobile Menu Button',
		'show_in_rest' => 0,
		'qef_simple_location_rules' => false,
	) );
	
	acf_add_local_field_group( array(
		'key' => 'group_663ab48c54d97',
		'title' => 'Mobile Menu Container',
		'fields' => array(
			array(
				'key' => 'field_663ab491e94d3',
				'label' => 'Menu Slug',
				'name' => 'menu_slug',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'rs-utility-blocks/mobile-menu-container',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '[RS Utility Blocks] ACF Block -> Mobile Menu Container',
		'show_in_rest' => 0,
		'qef_simple_location_rules' => false,
	) );
	
	acf_add_local_field_group( array(
		'key' => 'group_65f2327831337',
		'title' => 'Post Field',
		'fields' => array(
			array(
				'key' => 'field_663e504fa21d5',
				'label' => 'Selection',
				'name' => 'selection',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => 0,
				'allow_bulkedit' => 0,
				'allow_quickedit' => 0,
				'show_column' => 0,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'choices' => array(
					'post' => 'Current post',
					'post_parent' => 'Parent post',
					'specific_post' => 'Specific post',
				),
				'default_value' => 'post',
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_663e5118a21d6',
				'label' => 'Specific Post',
				'name' => 'specific_post',
				'aria-label' => '',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_663e504fa21d5',
							'operator' => '==',
							'value' => 'specific_post',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => 0,
				'allow_quickedit' => 0,
				'show_column' => 0,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'post_type' => '',
				'post_status' => '',
				'taxonomy' => '',
				'return_format' => 'id',
				'multiple' => 0,
				'allow_null' => 0,
				'bidirectional' => 0,
				'ui' => 1,
				'bidirectional_target' => array(
				),
			),
			array(
				'key' => 'field_65f23278347e0',
				'label' => 'Post Field',
				'name' => 'post_display_field',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => 0,
				'allow_bulkedit' => 0,
				'allow_quickedit' => 0,
				'show_column' => 0,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'choices' => array(
					'ID' => 'ID',
					'post_author' => 'Author',
					'post_date' => 'Publish Date',
					'post_date_gmt' => 'Publish Date (GMT)',
					'post_modified' => 'Modified Date',
					'post_modified_gmt' => 'Modified Date (GMT)',
					'post_content' => 'Content',
					'post_title' => 'Title',
					'post_excerpt' => 'Excerpt',
					'post_status' => 'Post Status',
					'comment_status' => 'Comment Status',
					'post_name' => 'Post Name (Slug)',
					'permalink' => 'Permalink',
					'guid' => 'GUID',
					'post_type' => 'Post Type',
					'comment_count' => 'Comment Count',
					'featured_image' => 'Featured Image',
					'custom_field' => 'Custom Field',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 1,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_663e5b96ab779',
				'label' => 'Image Size',
				'name' => 'image_size',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_65f23278347e0',
							'operator' => '==',
							'value' => 'featured_image',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => 0,
				'allow_bulkedit' => 0,
				'allow_quickedit' => 0,
				'show_column' => 0,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'choices' => array(
					'thumbnail' => 'Thumbnail (150x150, cropped)',
					'medium' => 'Medium (300x300)',
					'medium_large' => 'Medium Large (768x0)',
					'large' => 'Large (1024x1024)',
					'1536x1536' => '1536x1536 (1536x1536)',
					'2048x2048' => '2048x2048 (2048x2048)',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 1,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_663e5c09260ad',
				'label' => 'Date Format',
				'name' => 'date_format',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_65f23278347e0',
							'operator' => '==',
							'value' => 'post_date',
						),
					),
					array(
						array(
							'field' => 'field_65f23278347e0',
							'operator' => '==',
							'value' => 'post_date_gmt',
						),
					),
					array(
						array(
							'field' => 'field_65f23278347e0',
							'operator' => '==',
							'value' => 'post_modified',
						),
					),
					array(
						array(
							'field' => 'field_65f23278347e0',
							'operator' => '==',
							'value' => 'post_modified_gmt',
						),
					),
					array(
						array(
							'field' => 'field_65f23278347e0',
							'operator' => '==',
							'value' => 'custom_field',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => 0,
				'allow_bulkedit' => 0,
				'allow_quickedit' => 0,
				'show_column' => 0,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'choices' => array(
					'F j, Y' => 'May 22, 2024 (Site Default)',
					'F j, Y g:i a' => 'May 22, 2024 2:47 pm (Site Default)',
					'F j' => 'May 22',
					'Y-m-d' => '2024-05-22',
					'Y-m-d H:i:s' => '2024-05-22 14:47:59',
					'm/d/Y' => '05/22/2024',
					'm/d/Y g:i a' => '05/22/2024 2:47 pm',
					'd/m/Y' => '22/05/2024',
					'd/m/Y g:i a' => '22/05/2024 2:47 pm',
					'relative' => 'Relative',
					'custom' => 'Custom',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 1,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_663e665bdc957',
				'label' => 'Date Format (Custom)',
				'name' => 'date_format_custom',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_663e5c09260ad',
							'operator' => '==',
							'value' => 'custom',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => 0,
				'show_column_filter' => false,
				'allow_bulkedit' => 0,
				'allow_quickedit' => 0,
				'show_column' => 0,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'default_value' => 'F j, Y',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_65f23278383c1',
				'label' => 'Custom Field Key',
				'name' => 'custom_field_key',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_65f23278347e0',
							'operator' => '==',
							'value' => 'custom_field',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => 'first_name',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_663e515ea21d7',
				'label' => 'Default Value',
				'name' => 'default_value',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => 0,
				'show_column_filter' => false,
				'allow_bulkedit' => 0,
				'allow_quickedit' => 0,
				'show_column' => 0,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_65f232783bd00',
				'label' => 'Create Link',
				'name' => 'create_link',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => 'acf-hide-label',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'message' => 'Link to this field',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_65f2327843203',
				'label' => 'Link Type',
				'name' => 'link_type',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_65f232783bd00',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => 0,
				'allow_bulkedit' => 0,
				'allow_quickedit' => 0,
				'show_column' => 0,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'choices' => array(
					'post' => 'Permalink',
					'archive' => 'Post Type Archive',
					'parent' => 'Parent Post',
					'author' => 'Post Author',
					'edit' => 'Edit Post URL',
					'custom' => 'Custom URL',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 1,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_65f2327846ea4',
				'label' => 'Custom URL',
				'name' => 'custom_url',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_65f232783bd00',
							'operator' => '==',
							'value' => '1',
						),
						array(
							'field' => 'field_65f2327843203',
							'operator' => '==',
							'value' => 'custom',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_65f232783f7ae',
				'label' => 'New Tab',
				'name' => 'new_tab',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_65f232783bd00',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => 'acf-hide-label',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'message' => 'Open link in new tab',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_65f232784a86e',
				'label' => 'Apply Formatting',
				'name' => 'apply_formatting',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => 'acf-hide-label',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => 0,
				'allow_bulkedit' => 0,
				'allow_quickedit' => 0,
				'show_column' => 0,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'message' => 'Apply paragraph formatting',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_65f232784e3d4',
				'label' => 'Show filter (for developers)',
				'name' => 'show_filter_instructions_for_developers',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => 'acf-hide-label',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'message' => 'Show filter (for developers)',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_65f2327852088',
				'label' => 'Filter Usage',
				'name' => '',
				'aria-label' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_65f232784e3d4',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => 'acf-hide-label',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'message' => '<p>Developers can change the value of this block using a filter, for example:</p>

<pre class="code" style="overflow: auto; padding: 5px; background: #00000010;">add_filter( \'rs/post_field\', function( $value, $post_id, $display_field, $custom_field_key, $block ) {
		// Example values:
		// $value = null
		// $post_id = Post ID
		// $display_field = "custom_field"
		// $custom_field_key = "birthday"
		// $block = array

		// [Example] Apply date formatting to a custom date field
		if ( $display_field == \'custom_field\' && $field_key == \'expiration_date\' ) {
				$value = get_post_meta( $post_id, \'expiration_date\', true );
				if ( $value ) $value = date( \'F j, Y\', strtotime($value) );
		}

		return $value;
}, 10, 4);</pre>',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'rs-utility-blocks/post-field',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '[RS Utility Blocks] ACF Block -> Post Field',
		'show_in_rest' => 0,
		'qef_simple_location_rules' => 0,
	) );
	
	acf_add_local_field_group( array(
		'key' => 'group_65ee276b37a9f',
		'title' => 'User Field',
		'fields' => array(
			array(
				'key' => 'field_65ee276b1579b',
				'label' => 'User Profile Field',
				'name' => 'user_profile_display_field',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'choices' => array(
					'ID' => 'ID',
					'user_login' => 'Username',
					'user_nicename' => 'Nicename',
					'user_email' => 'Email',
					'user_url' => 'URL',
					'display_name' => 'Display Name',
					'first_name' => 'First Name',
					'last_name' => 'Last Name',
					'description' => 'Description',
					'nickname' => 'Nickname',
					'role' => 'Role',
					'avatar' => 'Avatar',
					'logout' => 'Sign Out',
					'custom_field' => 'Custom Field',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 1,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_65f2168a6b8da',
				'label' => 'Custom Field Key',
				'name' => 'custom_field_key',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_65ee276b1579b',
							'operator' => '==',
							'value' => 'custom_field',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => 'first_name',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_65ee2ca65d13d',
				'label' => 'Create Link',
				'name' => 'create_link',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => 'acf-hide-label',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'message' => 'Link to this field',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_65ee2cd392752',
				'label' => 'Link Type',
				'name' => 'link_type',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_65ee2ca65d13d',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'choices' => array(
					'profile' => 'Edit Profile',
					'author_url' => 'Author URL',
					'user_url' => 'User Website',
					'logout' => 'Sign Out',
					'custom' => 'Custom URL',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 1,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_65ee2e1892753',
				'label' => 'Custom URL',
				'name' => 'custom_url',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_65ee2ca65d13d',
							'operator' => '==',
							'value' => '1',
						),
						array(
							'field' => 'field_65ee2cd392752',
							'operator' => '==',
							'value' => 'custom',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_65ee3410e76cf',
				'label' => 'New Tab',
				'name' => 'new_tab',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_65ee2ca65d13d',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => 'acf-hide-label',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'message' => 'Open link in new tab',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_65f2213285afc',
				'label' => 'Apply Formatting',
				'name' => 'apply_formatting',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => 'acf-hide-label',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'message' => 'Apply paragraph formatting',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_65f21b106b8dd',
				'label' => 'Show filter (for developers)',
				'name' => 'show_filter_instructions_for_developers',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => 'acf-hide-label',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'message' => 'Show filter (for developers)',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_65f218f96b8dc',
				'label' => 'Filter Usage',
				'name' => '',
				'aria-label' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_65f21b106b8dd',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => 'acf-hide-label',
					'id' => '',
				),
				'allow_backendsearch' => false,
				'show_column_filter' => false,
				'allow_bulkedit' => false,
				'allow_quickedit' => false,
				'show_column' => false,
				'show_column_weight' => 1000,
				'show_column_sortable' => false,
				'message' => '<p>Developers can change the value of this block using a filter, for example:</p>

<pre class="code" style="overflow: auto; padding: 5px; background: #00000010;">add_filter( \'rs/user_field/custom_field\', function( $value, $user_id, $display_field, $custom_field_key ) {
		// Example values:
		// $value = null
		// $user_id = int(1)
		// $display_field = "custom_field"
		// $custom_field_key = "birthday"

		// [Example] Apply date formatting to a date field
		if ( $display_field == \'custom_field\' && $field_key == \'birthday\' ) {
				$value = get_user_meta( $user_id, \'birthday\', true );
				if ( $value ) $value = date( \'F j, Y\', strtotime($value) );
		}

		return $value;
}, 10, 4);</pre>',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'rs-utility-blocks/user-field',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '[RS Utility Blocks] ACF Block -> User Field',
		'show_in_rest' => 0,
		'qef_simple_location_rules' => false,
	) );
} );